In [21]:
import numpy as np
import utils
import importlib

importlib.reload(utils)
from utils import *

In [22]:
# A = get_random_hermite_matrix(100)
A = get_random_matrix(100, hermite=True)
alphas, betas, vs = lanczos_iteration(A, 10)
T = get_tridiagonal_matrix(alphas, betas)
vk, lambdak = power_iteration(T, 10)

In [41]:
vs[3] @ vs[4]

-1.2420620087993939e-15

In [23]:
vlan = np.conj(vk) @ vs

In [24]:
A @ vlan

array([4.91498512, 4.81349512, 5.00246747, 5.24203923, 4.93746426,
       4.89495488, 4.89234213, 4.88389584, 5.15701522, 4.93589173,
       4.9416432 , 5.04501061, 4.99333169, 5.02398896, 5.06600286,
       4.70069679, 5.04847262, 4.67912543, 5.1902065 , 5.17345605,
       4.94521146, 4.74949251, 5.55208483, 4.86500172, 4.82632761,
       5.15566548, 4.95102382, 5.044861  , 4.59679342, 4.6427163 ,
       4.97586136, 5.11930607, 4.9491157 , 4.97023633, 5.03316081,
       5.14707985, 4.90158196, 5.01871034, 5.09617557, 5.12351705,
       4.92090979, 5.23879307, 4.7748836 , 5.21471981, 5.22193869,
       4.70758782, 5.09639718, 5.18065696, 4.83201732, 4.95317756,
       5.02034964, 4.92989984, 4.68137351, 4.59351105, 4.91655965,
       5.0547009 , 5.05857407, 4.72155982, 4.62407662, 4.68672724,
       4.84068631, 4.66647747, 4.68165719, 5.0520555 , 4.67195326,
       5.26026465, 5.02623663, 4.8917566 , 4.9844859 , 5.04830259,
       4.96152114, 4.95534836, 4.63878944, 5.11429583, 5.07495

In [25]:
lambdak[-1] * vlan

array([4.91498512, 4.81349512, 5.00246747, 5.24203923, 4.93746426,
       4.89495488, 4.89234213, 4.88389584, 5.15701522, 4.93589173,
       4.9416432 , 5.04501061, 4.99333169, 5.02398896, 5.06600286,
       4.70069679, 5.04847262, 4.67912543, 5.1902065 , 5.17345605,
       4.94521146, 4.74949251, 5.55208483, 4.86500172, 4.82632761,
       5.15566548, 4.95102382, 5.044861  , 4.59679342, 4.6427163 ,
       4.97586136, 5.11930607, 4.9491157 , 4.97023633, 5.03316081,
       5.14707985, 4.90158196, 5.01871034, 5.09617557, 5.12351705,
       4.92090979, 5.23879307, 4.7748836 , 5.21471981, 5.22193869,
       4.70758782, 5.09639718, 5.18065696, 4.83201732, 4.95317756,
       5.02034964, 4.92989984, 4.68137351, 4.59351105, 4.91655965,
       5.0547009 , 5.05857407, 4.72155982, 4.62407662, 4.68672724,
       4.84068631, 4.66647747, 4.68165719, 5.0520555 , 4.67195326,
       5.26026465, 5.02623663, 4.8917566 , 4.9844859 , 5.04830259,
       4.96152114, 4.95534836, 4.63878944, 5.11429583, 5.07495

In [26]:
lambdak[-1]

49.68793455508204

In [27]:
eig, v = np.linalg.eigh(A)

In [28]:
eig

array([-4.00576527e+00, -3.70284897e+00, -3.60014974e+00, -3.50702278e+00,
       -3.38890549e+00, -3.31619755e+00, -3.21155740e+00, -3.01487901e+00,
       -2.97649567e+00, -2.91327498e+00, -2.69773417e+00, -2.66990387e+00,
       -2.64004860e+00, -2.54115517e+00, -2.48198517e+00, -2.39181140e+00,
       -2.21391170e+00, -2.16878442e+00, -2.08345052e+00, -2.02770388e+00,
       -1.95915225e+00, -1.84141469e+00, -1.72992979e+00, -1.64490345e+00,
       -1.55478561e+00, -1.52259298e+00, -1.42814213e+00, -1.40760390e+00,
       -1.31718230e+00, -1.28802328e+00, -1.22021130e+00, -1.08549857e+00,
       -1.06718414e+00, -1.00872750e+00, -8.56386779e-01, -8.36292164e-01,
       -8.04766767e-01, -7.60243644e-01, -6.77266326e-01, -5.56674450e-01,
       -5.37105088e-01, -5.03841175e-01, -4.34046451e-01, -4.12376299e-01,
       -3.66767887e-01, -3.28228453e-01, -2.19380927e-01, -1.77885191e-01,
       -1.11392935e-01, -4.19158569e-02,  3.21630871e-02,  9.34894708e-02,
        1.82743195e-01,  

In [29]:
v[-1]

array([-0.15760698, -0.13353424, -0.13384607,  0.01948966, -0.10555495,
       -0.12554134, -0.05213804,  0.01000222,  0.11736333,  0.06367414,
       -0.07226382, -0.10050639,  0.09284834,  0.1119556 , -0.0155996 ,
        0.16678776,  0.08729295,  0.07203277, -0.02246182, -0.2613651 ,
       -0.01559927, -0.10306325,  0.2169592 , -0.10117627, -0.01750902,
       -0.11129658,  0.00076857,  0.15285359,  0.09953666, -0.15241709,
       -0.02979116,  0.05514089,  0.06619303, -0.06042708,  0.04691512,
        0.06313722,  0.07824272,  0.0054972 , -0.09637519,  0.04304646,
       -0.19275348, -0.06862747,  0.06271416,  0.01746134, -0.17893643,
       -0.18858861, -0.02636441,  0.03034   ,  0.01407115, -0.15926139,
       -0.08948232,  0.19388486,  0.02194802, -0.04251748,  0.00754695,
       -0.03802971,  0.08336997,  0.08456813,  0.0685917 , -0.04531885,
       -0.04843773,  0.10877003, -0.09709963,  0.0694575 ,  0.11534647,
        0.05759894, -0.00438533, -0.13687945,  0.04036926, -0.02

In [30]:
alpha = v[-1] / vlan[0]

In [31]:
alpha * vlan

array([-0.15760698, -0.13077688, -0.13622841,  0.02078655, -0.10603771,
       -0.12502971, -0.05189784,  0.00993895,  0.12314269,  0.06394498,
       -0.07265577, -0.10316528,  0.09432838,  0.11443854, -0.01607891,
        0.15951598,  0.08966377,  0.06857607, -0.0237196 , -0.27510985,
       -0.0156952 , -0.09959301,  0.2450823 , -0.10014735, -0.01719319,
       -0.11674662,  0.0007742 ,  0.15689267,  0.09309274, -0.14397385,
       -0.03016015,  0.05743315,  0.06665268, -0.06110637,  0.04804315,
        0.06611868,  0.07802935,  0.00561321, -0.09992805,  0.04487282,
       -0.19298583, -0.07314877,  0.06092649,  0.0185262 , -0.19011147,
       -0.18063075, -0.02733752,  0.03197998,  0.01383363, -0.16049895,
       -0.09140059,  0.19447321,  0.02090482, -0.03973654,  0.00754936,
       -0.03911076,  0.08580559,  0.08124002,  0.06453189, -0.04321419,
       -0.0477055 ,  0.10327048, -0.09249004,  0.07139455,  0.10964292,
        0.06164528, -0.00448459, -0.13623255,  0.0409401 , -0.02